### ISSUE TITLE
@ilsvrc12 shrt 256

### ISSUE THREAD

**Issue by zyclonb** [HolmesShuan/AlexNet-BN-Caffemodel-on-ImageNet#1]
Sorry, could you explain more about the data set you used, @ilsvrc12 shrt 256? Is this a subset of ilsvrc12?

Thanks

**Comment by HolmesShuan** [comment]
Augmented training and testing sample: 
This improvement was first described by Andrew Howard [Andrew 2014]. Instead of resizing and cropping the image to 256x256, the image is proportionally resized to 256xN(Nx256) with the short edge to 256. Subcrops of 224x224 are then randomly extracted for training.
